server:
  port: 8083
spring:
  application:
    name: RATING-SERVICE
  config:
    import: configserver:http://localhost:8085
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservices

# Okta configuration for Rating service
okta:
  oauth2:
    issuer: https://dev-49167573.okta.com/oauth2/default
    audience: api://default

management:
  tracing:
    sampling:
      probability: 1.0