server:
  port: 8085
spring:
  application:
    name: CONFIG-SERVER


  cloud:
    config:
      server:
        git:
          uri: https://github.com/nitingakhar24/microservices-reviewsystem-config
          clone-on-start: true

management:
  tracing:
    sampling:
      probability: 1.0