server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE
  config:
    import: configserver:http://localhost:8085
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: root@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Okta configuration for Hotel service
okta:
  oauth2:
    issuer: https://dev-49167573.okta.com/oauth2/default
    audience: api://default

management:
  tracing:
    sampling:
      probability: 1.0